services:
  rabbitmq:
    image: rabbitmq:3.7.25-management-alpine
    ports:
      # Management console
      - "15673:15672"
  redis:
    image: redis
  command:
    image: c7_command
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
  query:
    image: c7_query
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_DATA_REDIS_HOST=redis
  reverse-proxy:
    image: nginx:latest
    ports:
      - "8180:80"
    volumes:
      - ./reverse_proxy.conf:/etc/nginx/conf.d/default.conf
